[package]
name = "search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.8.1"
serde_json = "1.0.113"
tantivy = "0.21.1"
tempfile = "3.9.0"
walkdir = "2.4.0"
