server:
  host: "0.0.0.0"
  port: 3030
repos:
  - name: "PLAT_2_7_644"
    type: "fs"
    path: "/mnt/Work/SVN/Platform/2_7_644"
  - name: "JYSK_1_2_205"
    type: "fs"
    path: "/mnt/Work/SVN/JYSK/1_2_205"
