repos:
  - name: "2_7_644"
    type: "fs"
    path: "/home/tlm/Projects/Enactor/2_7_644/"
indexer:
  use_temporary_index: true
  skip-patterns:
    - ".git"
    - "node_modules"
    - "dist"
    - "build"
    - "coverage"
    - "test"
    - "tests"
    - ".svn"
    - ".idea"
    - ".vscode"
    - ".DS_Store"
    - "target"