repos:
  - name: "PLAT_2_7_644"
    type: "fs"
    path: "/mnt/Work/SVN/Platform/2_7_644"
    allowed_file_extensions:
      - "java"
      - "xml"
    skip_patterns:
      - ".git"
      - "node_modules"
      - "dist"
      - "dist"
      - "coverage"
      - "test"
      - "tests"
      - ".svn"
      - ".idea"
      - ".vscode"
      - ".DS_Store"
      - "target"
  - name: "JYSK_1_2_205"
    type: "fs"
    path: "/mnt/Work/SVN/JYSK/1_2_205"
    allowed_file_extensions:
      - "java"
      - "xml"
    skip_patterns:
      - ".git"
      - "node_modules"
      - "dist"
      - "dist"
      - "coverage"
      - "test"
      - "tests"
      - ".svn"
      - ".idea"
      - ".vscode"
      - ".DS_Store"
      - "target"
indexer:
  use_temporary_index: false
  index_path: "/home/tlm/Projects/codesearch-rs/tmp"
  force_reindex: false